Fix build failing when defining signals with Gdk.ScrollEvent
I suspect this is a bug of Vala. It tries to call gdk_value_get_event() which
does not exist and fails to build with the following error message:

    ../src/Widgets/DisplayWidget.vala: In function ‘g_cclosure_user_marshal_VOID__GDK_EVENT’:
    ../src/Widgets/DisplayWidget.vala:18:19: error: implicit declaration of function ‘gdk_value_get_event’; did you mean ‘g_value_get_uint’? [-Wimplicit-function-declaration]
       18 | public class Sound.DisplayWidget : Gtk.Box {
          |                   ^~~~~~~~~~~~~~~~~~~
          |                   g_value_get_uint
    ../src/Widgets/DisplayWidget.vala:18:19: error: passing argument 2 of ‘callback’ makes pointer from integer without a cast [-Wint-conversion]
       18 | public class Sound.DisplayWidget : Gtk.Box {
          |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
          |                   |
          |                   int

This commit resolves the above build error by wrapping Gdk.ScrollEvent with
GLib.Value.